// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.labeler.rule
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Annotate<'a> {
    pub adult_content: bool,
    #[serde(borrow)]
    pub default_setting: jacquard_common::CowStr<'a>,
}

pub mod annotate_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type DefaultSetting;
        type AdultContent;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type DefaultSetting = Unset;
        type AdultContent = Unset;
    }
    ///State transition - sets the `default_setting` field to Set
    pub struct SetDefaultSetting<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDefaultSetting<S> {}
    impl<S: State> State for SetDefaultSetting<S> {
        type DefaultSetting = Set<members::default_setting>;
        type AdultContent = S::AdultContent;
    }
    ///State transition - sets the `adult_content` field to Set
    pub struct SetAdultContent<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAdultContent<S> {}
    impl<S: State> State for SetAdultContent<S> {
        type DefaultSetting = S::DefaultSetting;
        type AdultContent = Set<members::adult_content>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `default_setting` field
        pub struct default_setting(());
        ///Marker type for the `adult_content` field
        pub struct adult_content(());
    }
}

/// Builder for constructing an instance of this type
pub struct AnnotateBuilder<'a, S: annotate_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<bool>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Annotate<'a> {
    /// Create a new builder for this type
    pub fn new() -> AnnotateBuilder<'a, annotate_state::Empty> {
        AnnotateBuilder::new()
    }
}

impl<'a> AnnotateBuilder<'a, annotate_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        AnnotateBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AnnotateBuilder<'a, S>
where
    S: annotate_state::State,
    S::AdultContent: annotate_state::IsUnset,
{
    /// Set the `adultContent` field (required)
    pub fn adult_content(
        mut self,
        value: impl Into<bool>,
    ) -> AnnotateBuilder<'a, annotate_state::SetAdultContent<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        AnnotateBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AnnotateBuilder<'a, S>
where
    S: annotate_state::State,
    S::DefaultSetting: annotate_state::IsUnset,
{
    /// Set the `defaultSetting` field (required)
    pub fn default_setting(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> AnnotateBuilder<'a, annotate_state::SetDefaultSetting<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        AnnotateBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AnnotateBuilder<'a, S>
where
    S: annotate_state::State,
    S::DefaultSetting: annotate_state::IsSet,
    S::AdultContent: annotate_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Annotate<'a> {
        Annotate {
            adult_content: self.__unsafe_private_named.0.unwrap(),
            default_setting: self.__unsafe_private_named.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Annotate<'a> {
        Annotate {
            adult_content: self.__unsafe_private_named.0.unwrap(),
            default_setting: self.__unsafe_private_named.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_net_gifdex_labeler_rule() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("net.gifdex.labeler.rule"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("annotate"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: None,
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("defaultSetting"),
                            ::jacquard_common::smol_str::SmolStr::new_static("adultContent")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::std::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "adultContent",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Boolean(::jacquard_lexicon::lexicon::LexBoolean {
                                description: None,
                                default: None,
                                r#const: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "defaultSetting",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: None,
                    key: Some(::jacquard_common::CowStr::new_static("any")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: Some(
                            vec![
                                ::jacquard_common::smol_str::SmolStr::new_static("name"),
                                ::jacquard_common::smol_str::SmolStr::new_static("description"),
                                ::jacquard_common::smol_str::SmolStr::new_static("behaviour"),
                                ::jacquard_common::smol_str::SmolStr::new_static("createdAt")
                            ],
                        ),
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::std::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "behaviour",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: None,
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("#annotate"),
                                        ::jacquard_common::CowStr::new_static("#moderate")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "createdAt",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: None,
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "description",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: None,
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: Some(200usize),
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("name"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: None,
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: Some(20usize),
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "selfLabel",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Boolean(::jacquard_lexicon::lexicon::LexBoolean {
                                    description: None,
                                    default: None,
                                    r#const: None,
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("moderate"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: None,
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("takedown")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::std::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("takedown"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Boolean(::jacquard_lexicon::lexicon::LexBoolean {
                                description: None,
                                default: None,
                                r#const: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map
        },
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Annotate<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.labeler.rule"
    }
    fn def_name() -> &'static str {
        "annotate"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_labeler_rule()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Rule<'a> {
    #[serde(borrow)]
    pub behaviour: RuleBehaviour<'a>,
    pub created_at: jacquard_common::types::string::Datetime,
    #[serde(borrow)]
    pub description: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub name: jacquard_common::CowStr<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub self_label: std::option::Option<bool>,
}

pub mod rule_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Description;
        type CreatedAt;
        type Name;
        type Behaviour;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Description = Unset;
        type CreatedAt = Unset;
        type Name = Unset;
        type Behaviour = Unset;
    }
    ///State transition - sets the `description` field to Set
    pub struct SetDescription<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDescription<S> {}
    impl<S: State> State for SetDescription<S> {
        type Description = Set<members::description>;
        type CreatedAt = S::CreatedAt;
        type Name = S::Name;
        type Behaviour = S::Behaviour;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Description = S::Description;
        type CreatedAt = Set<members::created_at>;
        type Name = S::Name;
        type Behaviour = S::Behaviour;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetName<S> {}
    impl<S: State> State for SetName<S> {
        type Description = S::Description;
        type CreatedAt = S::CreatedAt;
        type Name = Set<members::name>;
        type Behaviour = S::Behaviour;
    }
    ///State transition - sets the `behaviour` field to Set
    pub struct SetBehaviour<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetBehaviour<S> {}
    impl<S: State> State for SetBehaviour<S> {
        type Description = S::Description;
        type CreatedAt = S::CreatedAt;
        type Name = S::Name;
        type Behaviour = Set<members::behaviour>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `description` field
        pub struct description(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `behaviour` field
        pub struct behaviour(());
    }
}

/// Builder for constructing an instance of this type
pub struct RuleBuilder<'a, S: rule_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<RuleBehaviour<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<bool>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Rule<'a> {
    /// Create a new builder for this type
    pub fn new() -> RuleBuilder<'a, rule_state::Empty> {
        RuleBuilder::new()
    }
}

impl<'a> RuleBuilder<'a, rule_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RuleBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> RuleBuilder<'a, S>
where
    S: rule_state::State,
    S::Behaviour: rule_state::IsUnset,
{
    /// Set the `behaviour` field (required)
    pub fn behaviour(
        mut self,
        value: impl Into<RuleBehaviour<'a>>,
    ) -> RuleBuilder<'a, rule_state::SetBehaviour<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        RuleBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> RuleBuilder<'a, S>
where
    S: rule_state::State,
    S::CreatedAt: rule_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> RuleBuilder<'a, rule_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        RuleBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> RuleBuilder<'a, S>
where
    S: rule_state::State,
    S::Description: rule_state::IsUnset,
{
    /// Set the `description` field (required)
    pub fn description(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> RuleBuilder<'a, rule_state::SetDescription<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        RuleBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> RuleBuilder<'a, S>
where
    S: rule_state::State,
    S::Name: rule_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> RuleBuilder<'a, rule_state::SetName<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        RuleBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: rule_state::State> RuleBuilder<'a, S> {
    /// Set the `selfLabel` field (optional)
    pub fn self_label(mut self, value: impl Into<Option<bool>>) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `selfLabel` field to an Option value (optional)
    pub fn maybe_self_label(mut self, value: Option<bool>) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S> RuleBuilder<'a, S>
where
    S: rule_state::State,
    S::Description: rule_state::IsSet,
    S::CreatedAt: rule_state::IsSet,
    S::Name: rule_state::IsSet,
    S::Behaviour: rule_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Rule<'a> {
        Rule {
            behaviour: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            description: self.__unsafe_private_named.2.unwrap(),
            name: self.__unsafe_private_named.3.unwrap(),
            self_label: self.__unsafe_private_named.4,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Rule<'a> {
        Rule {
            behaviour: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            description: self.__unsafe_private_named.2.unwrap(),
            name: self.__unsafe_private_named.3.unwrap(),
            self_label: self.__unsafe_private_named.4,
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Rule<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, RuleRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RuleBehaviour<'a> {
    #[serde(rename = "net.gifdex.labeler.rule#annotate")]
    Annotate(Box<crate::net_gifdex::labeler::rule::Annotate<'a>>),
    #[serde(rename = "net.gifdex.labeler.rule#moderate")]
    Moderate(Box<crate::net_gifdex::labeler::rule::Moderate<'a>>),
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct RuleGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Rule<'a>,
}

impl From<RuleGetRecordOutput<'_>> for Rule<'_> {
    fn from(output: RuleGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Rule<'_> {
    const NSID: &'static str = "net.gifdex.labeler.rule";
    type Record = RuleRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct RuleRecord;
impl jacquard_common::xrpc::XrpcResp for RuleRecord {
    const NSID: &'static str = "net.gifdex.labeler.rule";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = RuleGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for RuleRecord {
    const NSID: &'static str = "net.gifdex.labeler.rule";
    type Record = RuleRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Rule<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.labeler.rule"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_labeler_rule()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        {
            let value = &self.description;
            {
                let count = ::unicode_segmentation::UnicodeSegmentation::graphemes(
                        value.as_ref(),
                        true,
                    )
                    .count();
                if count > 200usize {
                    return Err(::jacquard_lexicon::validation::ConstraintError::MaxGraphemes {
                        path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                            "description",
                        ),
                        max: 200usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.name;
            {
                let count = ::unicode_segmentation::UnicodeSegmentation::graphemes(
                        value.as_ref(),
                        true,
                    )
                    .count();
                if count > 20usize {
                    return Err(::jacquard_lexicon::validation::ConstraintError::MaxGraphemes {
                        path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                            "name",
                        ),
                        max: 20usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Moderate<'a> {
    pub takedown: bool,
}

pub mod moderate_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Takedown;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Takedown = Unset;
    }
    ///State transition - sets the `takedown` field to Set
    pub struct SetTakedown<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTakedown<S> {}
    impl<S: State> State for SetTakedown<S> {
        type Takedown = Set<members::takedown>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `takedown` field
        pub struct takedown(());
    }
}

/// Builder for constructing an instance of this type
pub struct ModerateBuilder<'a, S: moderate_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (::core::option::Option<bool>,),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Moderate<'a> {
    /// Create a new builder for this type
    pub fn new() -> ModerateBuilder<'a, moderate_state::Empty> {
        ModerateBuilder::new()
    }
}

impl<'a> ModerateBuilder<'a, moderate_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ModerateBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ModerateBuilder<'a, S>
where
    S: moderate_state::State,
    S::Takedown: moderate_state::IsUnset,
{
    /// Set the `takedown` field (required)
    pub fn takedown(
        mut self,
        value: impl Into<bool>,
    ) -> ModerateBuilder<'a, moderate_state::SetTakedown<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        ModerateBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ModerateBuilder<'a, S>
where
    S: moderate_state::State,
    S::Takedown: moderate_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Moderate<'a> {
        Moderate {
            takedown: self.__unsafe_private_named.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Moderate<'a> {
        Moderate {
            takedown: self.__unsafe_private_named.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Moderate<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.labeler.rule"
    }
    fn def_name() -> &'static str {
        "moderate"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_labeler_rule()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}