// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.actor.getPosts
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPosts<'a> {
    #[serde(borrow)]
    pub actor: jacquard_common::types::string::Did<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    ///(default: 50, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
}

pub mod get_posts_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetActor<S> {}
    impl<S: State> State for SetActor<S> {
        type Actor = Set<members::actor>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetPostsBuilder<'a, S: get_posts_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<i64>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetPosts<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetPostsBuilder<'a, get_posts_state::Empty> {
        GetPostsBuilder::new()
    }
}

impl<'a> GetPostsBuilder<'a, get_posts_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetPostsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetPostsBuilder<'a, S>
where
    S: get_posts_state::State,
    S::Actor: get_posts_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> GetPostsBuilder<'a, get_posts_state::SetActor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetPostsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: get_posts_state::State> GetPostsBuilder<'a, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: get_posts_state::State> GetPostsBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> GetPostsBuilder<'a, S>
where
    S: get_posts_state::State,
    S::Actor: get_posts_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetPosts<'a> {
        GetPosts {
            actor: self.__unsafe_private_named.0.unwrap(),
            cursor: self.__unsafe_private_named.1,
            limit: self.__unsafe_private_named.2,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPostsOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub feed: Vec<crate::net_gifdex::feed::PostFeedView<'a>>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetPostsError<'a> {
    /// The requested actor does not exist or has not been indexed yet.
    #[serde(rename = "ActorNotFound")]
    ActorNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl std::fmt::Display for GetPostsError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ActorNotFound(msg) => {
                write!(f, "ActorNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///net.gifdex.actor.getPosts
pub struct GetPostsResponse;
impl jacquard_common::xrpc::XrpcResp for GetPostsResponse {
    const NSID: &'static str = "net.gifdex.actor.getPosts";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetPostsOutput<'de>;
    type Err<'de> = GetPostsError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetPosts<'a> {
    const NSID: &'static str = "net.gifdex.actor.getPosts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetPostsResponse;
}

/// Endpoint type for
///net.gifdex.actor.getPosts
pub struct GetPostsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetPostsRequest {
    const PATH: &'static str = "/xrpc/net.gifdex.actor.getPosts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetPosts<'de>;
    type Response = GetPostsResponse;
}